[package]
name = "disparity_map"
version = "0.1.0"
edition = "2024"

[lib]
name = "disparity_map"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pixels = "0.15.0"
png = "0.18.0"
wasm-bindgen = "0.2"
wgpu = "26.0.1"
winit = "0.30.12"
